### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by Likaos** [KartulUdus/PoTatoCheck#1]
Hello,

A problem with the login check, any idea ?

Fresh install, format from accounts.csv

ptc,test,test
ptc,test2,test

Traceback (most recent call last):
  File "logincheck.py", line 67, in <module>
    for g, group in groupby(ac, key=lambda _, c=count(): c.next()/jobs):
  File "logincheck.py", line 67, in <lambda>
    for g, group in groupby(ac, key=lambda _, c=count(): c.next()/jobs):
ZeroDivisionError: integer division or modulo by zero

Thanks

**Comment by KartulUdus** [comment]
This happens when you try to check less accounts than default threads.

Threads default to the number of logical cpu cores you have.

Can you try to launch with `-th 1` and see if the issue goes away?

**Comment by Likaos** [comment]
It works
Can you add it on your documentation or maybe set it at 1 for the next noob users like me ?

Thanks :)

**Comment by KartulUdus** [comment]
A check against this existed in pw changer and email resender, 
added to logincheck now, it will say something like 
` [      MainThread][    logincheck][CRITICAL] 1 accounts, but 4 threads, Need fewer threads`
in the future
